"""Named signals over file offset, and window classification.

Generalises the reference's fixed two-series plot view: any number of named
signals, each a float series with natural (lo, hi) bounds for normalisation.

Classification thresholds are NOT hardcoded: they come from
corpus/calibration.json, generated by corpus/calibrate.py from measured
corpus samples (§5.3 — the 7.0-means-packed folklore is window-size-
dependent nonsense). Change a window size, re-run calibration, and the
thresholds move with it.
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass

import numpy as np

from .stats import window_stats

DECISION_WINDOW = 4096   # decisions
DISPLAY_WINDOW = 256     # visual texture (matches the reference)


@dataclass
class Signal:
    name: str
    unit: str
    values: np.ndarray     # float32
    offsets: np.ndarray    # int64
    lo: float
    hi: float              # natural range for normalisation


# name -> (window, stride, stat key, unit, lo, hi)
SIGNALS: dict[str, tuple[int, int, str, str, float, float]] = {
    "entropy_256":     (DISPLAY_WINDOW, DISPLAY_WINDOW, "entropy", "bits/byte", 0.0, 8.0),
    "entropy_4096":    (DECISION_WINDOW, DECISION_WINDOW, "entropy", "bits/byte", 0.0, 8.0),
    "printable_ratio": (DECISION_WINDOW, DECISION_WINDOW, "printable_ratio", "ratio", 0.0, 1.0),
    "null_ratio":      (DECISION_WINDOW, DECISION_WINDOW, "null_ratio", "ratio", 0.0, 1.0),
    "chi2_uniform":    (DECISION_WINDOW, DECISION_WINDOW, "chi2", "chi2", 0.0, 1024.0),
    "distinct_bytes":  (DECISION_WINDOW, DECISION_WINDOW, "distinct", "count", 0.0, 256.0),
}


def compute_signals(buf, names: list[str] | None = None,
                    progress=None) -> dict[str, Signal]:
    """Compute named signals, sharing one counting pass per (window, stride).

    `progress`, when given, is called with an overall fraction in (0, 1],
    weighted by each pass's window count (the 256-byte pass is ~16x the
    4096-byte pass's work)."""
    names = list(SIGNALS) if names is None else names
    unknown = [n for n in names if n not in SIGNALS]
    if unknown:
        raise KeyError(f"unknown signals {unknown}; known: {list(SIGNALS)}")
    groups: dict[tuple[int, int], list[str]] = {}
    for n in names:
        w, s, *_ = SIGNALS[n]
        groups.setdefault((w, s), []).append(n)
    weights = {g: max(1, len(buf) // g[1]) for g in groups}
    w_total = sum(weights.values())
    w_done = 0
    out: dict[str, Signal] = {}
    for (w, s), members in groups.items():
        keys = tuple({SIGNALS[n][2] for n in members})
        cb = None
        if progress is not None:
            base, share = w_done, weights[(w, s)]
            cb = lambda f, base=base, share=share: \
                progress((base + f * share) / w_total)
        stats = window_stats(buf, w, s, which=keys, progress=cb)
        w_done += weights[(w, s)]
        for n in members:
            _, _, key, unit, lo, hi = SIGNALS[n]
            out[n] = Signal(name=n, unit=unit, values=stats[key],
                            offsets=stats["offsets"], lo=lo, hi=hi)
    return out


# ------------------------------------------------------------ calibration

_FALLBACK_CAL = {
    # Conservative defaults for a source checkout whose corpus has not been
    # built yet. **Not a shipping mode** — plan §5.3's whole argument is
    # that thresholds come from a checked-in calibration.json, and these
    # numbers are the folklore it exists to replace (`code_h_lo` alone is
    # 0.8 bits off the measured value). A wheel that landed here would give
    # different verdicts from a checkout, which is why the file is staged
    # into the package by tools/build_ui.py and asserted in the release
    # workflow. `load_calibration()["source"]` says which one is in force,
    # and /api/config reports it.
    "derived": {
        "random_h_min": 7.90, "random_chi2_max": 400.0,
        "packed_h_min": 7.20, "code_h_lo": 4.5, "code_h_hi": 7.0,
        "ascii_printable_min": 0.95, "zero_null_min": 0.995,
    },
    "source": "fallback-defaults",
}

_cal_cache: dict | None = None


def _find_calibration() -> str | None:
    """The thresholds in force, most specific source first.

    The packaged copy is deliberately **last**. It is staged at build time
    from `corpus/calibration.json`, so in a checkout it is at best identical
    to the repo copy and at worst stale — and a developer who has just re-run
    `corpus/calibrate.py` must see the numbers they measured, not the ones
    that were current when the package data was staged.
    """
    env = os.environ.get("BINVIZ_CALIBRATION")
    if env and os.path.exists(env):
        return env
    # repo layout: src/binviz/signals.py -> repo root -> corpus/
    here = os.path.dirname(os.path.abspath(__file__))
    repo = os.path.join(here, "..", "..", "corpus", "calibration.json")
    if os.path.exists(repo):
        return os.path.abspath(repo)
    cwd = os.path.join(os.getcwd(), "corpus", "calibration.json")
    if os.path.exists(cwd):
        return cwd
    # installed: staged into the package by tools/build_ui.py, because
    # `corpus/` is not in the wheel and a pip install would otherwise run
    # on _FALLBACK_CAL without ever saying so.
    packaged = os.path.join(here, "calibration.json")
    if os.path.exists(packaged):
        return packaged
    return None


def load_calibration() -> dict:
    global _cal_cache
    if _cal_cache is None:
        path = _find_calibration()
        if path:
            with open(path, encoding="utf-8") as f:
                _cal_cache = json.load(f)
        else:
            _cal_cache = _FALLBACK_CAL
    return _cal_cache


def classify(window_bytes, cal: dict | None = None) -> str:
    """Classify one window: zero | ascii | code | data | compressed |
    encrypted_or_random.

    Compressed and encrypted data have near-identical entropy; the weak
    distinguisher is chi-square (compressed streams keep small structural
    biases). That call is low-confidence by nature — the caller must not
    present compressed-vs-encrypted as certain.
    """
    t = (cal or load_calibration())["derived"]
    a = np.frombuffer(window_bytes, dtype=np.uint8)
    if a.size == 0:
        return "zero"
    counts = np.bincount(a, minlength=256).astype(np.float64)
    n = a.size
    if counts[0] / n >= t["zero_null_min"]:
        return "zero"
    from .stats import _PRINTABLE_MASK  # shared byte-class mask
    if counts[_PRINTABLE_MASK].sum() / n >= t["ascii_printable_min"]:
        return "ascii"
    p = counts / n
    nzp = p[p > 0]
    h = float(-(nzp * np.log2(nzp)).sum())
    e = n / 256.0
    chi2 = float(((counts - e) ** 2).sum() / e)
    if h >= t["random_h_min"] and chi2 <= t["random_chi2_max"]:
        return "encrypted_or_random"
    if h >= t["packed_h_min"]:
        return "compressed"
    if t["code_h_lo"] <= h <= t["code_h_hi"]:
        return "code"
    return "data"


def classify_profile(buf, window: int = DECISION_WINDOW,
                     cal: dict | None = None) -> list[str]:
    """Classify every full window of a buffer."""
    a = np.frombuffer(buf, dtype=np.uint8)
    return [classify(a[i : i + window], cal)
            for i in range(0, len(a) - window + 1, window)]
